name: ci-staging-deploy

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_LAMBDA_NAME: test-lamdba-deploy
  PIP_REQUIREMENTS: requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: install python packages
        run: |
          set -o errexit
          set -o nounset
          set -o pipefail

          PACK_DIR=$(pwd)/package
          ZIP_FILE=function.zip

          python -m pip install --upgrade pip
          pip install --target ${PACK_DIR} -r ${PIP_REQUIREMENTS}
          # cp -r lambda ${PACKAGE_NAME} ${PACK_DIR}
          cp -r lambda_function.py ${PACK_DIR}
          (cd ${PACK_DIR} && zip -r9 ${OLDPWD}/${ZIP_FILE} .)
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: function-zip
          path: function.zip
  upload:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: amazon/aws-cli
      env:
        AWS_REGION: ap-northeast-1
        AWS_DEFAULT_REGION: ap-northeast-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: function-zip
      - name: upload to lambda
        run: |
          aws lambda update-function-code --function-name ${AWS_LAMBDA_NAME} --zip-file fileb://function.zip
