name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: action-test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2

      - name: preparing test tools
        run: sudo npm install -g pyright

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements.txt
